name: CI/CD Pipeline with Aqua Security Scan and SBOM

on:
  push:
    branches:
      - main

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install
      working-directory: ./app
    - name: Run tests
      run: npm test
      working-directory: ./app

  build_image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.CI_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build and Push Docker Image
      run: |
        IMAGE_NAME="bakery-app"
        docker build -t ghcr.io/${{ github.repository }}/$IMAGE_NAME:${{ github.sha }} .
        docker push ghcr.io/${{ github.repository }}/$IMAGE_NAME:${{ github.sha }}

  aqua_sbom:
    runs-on: ubuntu-latest
    needs: build_image
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run Aqua SBOM and Code Scan
      uses: docker://aquasec/aqua-scanner
      with:
        args: trivy fs --scanners config,vuln,secret .
      env:
        AQUA_KEY: ${{ secrets.AQUA_KEY }}
        AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
        GITHUB_TOKEN: ${{ github.token }}
        AQUA_URL: https://api.dev.supply-chain.cloud.aquasec.com
        CSPM_URL: https://stage.api.cloudsploit.com
        TRIVY_RUN_AS_PLUGIN: 'aqua'
    - name: Manifest Generation
      run: |
        export BILLY_SERVER=https://billy.dev-aqua.codesec.aquasec.com
        curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
        curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
        if ! cat install.sh.checksum | sha256sum ; then
          echo "install.sh checksum failed"
          exit 1
        fi
        BINDIR="." sh install.sh
        rm install.sh install.sh.checksum
        ./billy generate \
          --access-token "${{ secrets.GITHUB_TOKEN }}" \
          --aqua-key "${{ secrets.AQUA_KEY }}" \
          --aqua-secret "${{ secrets.AQUA_SECRET }}" \
          --cspm-url https://stage.api.cloudsploit.com \
          --artifact-path "bakery-app:${{ github.sha }}"
