name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_image:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: bakery-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.CI_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: docker build -t ghcr.io/${{ github.repository }}/$IMAGE_NAME:${{ github.sha }} .

      - name: Push Docker Image
        run: docker push ghcr.io/${{ github.repository }}/$IMAGE_NAME:${{ github.sha }}

  scan_job:
    runs-on: ubuntu-latest
    needs: build_image
    env:
      IMAGE_TAG: ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
    steps:
      - name: Run Aqua Security Scan
        run: |
          docker pull registry.aquasec.com/scanner:2022.4
          docker run --rm registry.aquasec.com/scanner:2022.4 scannercli scan -H ${{ secrets.AQUA_SERVER }} --token ${{ secrets.AQUA_TOKEN }} --registry "Github" $IMAGE_TAG --show-negligible --register-compliant --htmlfile aqua-scan.html >/dev/null

      - name: Upload Aqua Scan Results
        uses: actions/upload-artifact@v2
        with:
          name: aqua-scan-results
          path: aqua-scan.html
