name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.CI_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME="bakery-app"
          docker build -t ghcr.io/${{ github.repository }}/$IMAGE_NAME:${{ github.sha }} .
          docker push ghcr.io/${{ github.repository }}/$IMAGE_NAME:${{ github.sha }}

  scan_job:
    runs-on: ubuntu-latest  # This ensures an AMD64 architecture
    needs: build_image
    env:
      DOCKER_AUTH_CONFIG: ${{ secrets.DOCKER_AUTH_CONFIG }}  # Assuming you've added this secret in GitHub
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Login to Aqua Registry
        run: echo $DOCKER_AUTH_CONFIG > /home/runner/.docker/config.json

      - name: Pull Aqua Scanner
        run: docker pull registry.aquasec.com/scanner:2022.4

      - name: Debug Aqua Scanner Container
        run: |
          docker run --rm registry.aquasec.com/scanner:2022.4 /bin/sh -c "ls -al /; which scannercli; echo $PATH"



      - name: Upload Aqua Scan Results
        uses: actions/upload-artifact@v2
        with:
          name: aqua-scan-results
          path: aqua-scan.html









