name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_hello_world_image:
    runs-on: ubuntu-latest

    steps:
      - name: Debugging
        run: |
          echo "Listing all files"
          ls -al
          echo "Checking Docker version"
          docker --version

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/hello-world:${{ github.sha }} -f Dockerfile.hello .
          docker push ghcr.io/${{ github.repository }}/hello-world:${{ github.sha }}
